#!/bin/sh
### BEGIN INIT INFO
# Provides:          goTarino
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Tarino Bot is here to serve you!
### END INIT INFO

NAME="goTarino"

PROGRAM_PATH="/home/pi/4.py"
ERROR_PATH="/tmp/tarinoLog_error.txt"
LOG_PATH="/tmp/tarinoLog_normal.txt"
SCRIPT="python3 $PROGRAM_PATH >$ERROR_PATH 2>$LOG_PATH &"

RUNAS=pi

start() {
  echo 'Starting service…' >&2
  su -c "$SCRIPT" $RUNAS
  echo 'Service started' >&2
}

stop() {
  echo 'Stopping service…' >&2
  kill -9 $(ps aux | grep "[p]ython3 $PROGRAM_PATH" | awk '{print $2}')
  mv $LOG_PATH $LOG_PATH.bak
  mv $ERROR_PATH $ERROR_PATH.bak
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
esac
